<a href="https://colab.research.google.com/github/mrgunjan/mrgunjan/blob/main/DPP_Practical_01_gbj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1 **dimention** **

In [ ]:
gunjan=np.array([2,3,4,5])
gunjan

array([2, 3, 4, 5])

In [ ]:
gunjan[2]

4

In [ ]:
gunjan[2]=16
gunjan

array([ 2,  3, 16,  5])

In [ ]:
gunjan.dtype

dtype('int64')

In [ ]:
gunjan=np.array([2,3,4,5],np.int8)
gunjan

array([2, 3, 4, 5], dtype=int8)

In [ ]:
gunjan.dtype

dtype('int8')

In [ ]:
gunjan[2]=160
gunjan

array([  2,   3, -96,   5], dtype=int8)

In [ ]:
gunjan.dtype


dtype('int8')

In [ ]:
gunjan.size

4

In [ ]:
gunjan.shape

(4,)

2 ***dimention***

In [ ]:
gunjan=np.array([[2,3,4,5]],np.int)
gunjan

array([[2, 3, 4, 5]])

In [ ]:
gunjan.dtype

dtype('int64')

In [ ]:
gunjan.size

4

In [ ]:
gunjan.shape

(1, 4)

***3***/Multi demention

In [ ]:
b=np.array([[2,3,4],[6,7,8],[9,10,11]])
b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b.dtype

dtype('int64')

In [ ]:
b.shape

(3, 3)

In [ ]:
b.size

9

In [ ]:
c=np.array([[1,2,3]],np.int16)

In [ ]:
c.dtype

dtype('int16')